openapi: 3.0.0
info:
  title: MediSupply Integrity Gateway
  version: 1.0.0
servers:
  - url: https://{GATEWAY_ID}-{REGION}.gateway.dev
    variables:
      GATEWAY_ID:
        default: medi-supply-gw
      REGION:
        default: us-central1

paths:
  /inventory/products:
    post:
      summary: Create or update a product (via checksum validator proxy)
      operationId: postInventoryProducts
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/CF_NAME
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Created
        '200':
          description: Updated
        '400':
          description: Integrity or validation error
        '403':
          description: Integrity not validated
        '502':
          description: Upstream error

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header